"""add work time preferences to user

Revision ID: a708b77ad5b6
Revises: e120e7a5c33f
Create Date: 2026-04-16 01:25:21.317765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a708b77ad5b6'
down_revision = 'e120e7a5c33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_schedule_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_schedule_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_schedule_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_schedule_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
